items/urls.py
from django.urls import path
from . import views

app_name = 'items'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('item_detail/<int:id>/', views.item_detail, name='item_detail'),
    path('register/', views.register, name='register'),
    path('check_register/', views.check_register, name='check_register'),
    path('do_register/', views.do_register, name='do_register'),
    path("delete/<int:id>/", views.delete, name="delete"),
    path("update/<int:id>/", views.update, name="update"),
    path("like/<int:id>/", views.like, name="like"),
    path("like_list/", views.like_list, name="like_list"),
    path("register_item_list/", views.register_item_list, name="register_item_list"),
]

spartamarket/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='items/index/')),
    path('items/', include('items.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

items/models.py
from django.db import models
from django.conf import settings


class Item(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    click_count = models.IntegerField(default=0)
    price = models.IntegerField()
    deleted = models.BooleanField(default=False)

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="items")
    images = models.ForeignKey('Image', on_delete=models.CASCADE, related_name='item_images', blank=True, null=True)

    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_items"
    )

    def __str__(self):
        return self.title


class Image(models.Model):
    filepath = models.ImageField(upload_to='images/', blank=True)
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='item_images', default=1)

    def __str__(self):
        return self.filepath


class HashTag(models.Model):
    name = models.CharField(max_length=100, unique=True)


class TaggedItem(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="tagged_items")
    tag = models.ForeignKey(HashTag, on_delete=models.CASCADE, related_name="tagged_items")

items/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

items/views.py
from django.http import HttpRequest, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.views.decorators.http import *
from django.db.models import Count
from .models import *
from spartamarket.util import *

import json


def index(request: HttpRequest):
    category = request.GET.get('category')
    keyword = request.GET.get('keyword')
    sort = request.GET.get('sort')
    if not category:
        category = 'title'

    if not keyword:
        keyword = ''

    if not sort:
        sort = 'recent'

    item_list = None
    if category == 'title':
        item_list = Item.objects.filter(title__icontains=keyword)
    elif category == 'username':
        item_list = Item.objects.filter(user__username__icontains=keyword)
    elif category == 'content':
        item_list = Item.objects.filter(content__icontains=keyword)

    if sort == 'recent':
        item_list = item_list.order_by('-created_at')
    elif sort == 'click':
        item_list = item_list.all().order_by('-click_count')
    elif sort == 'like':
        item_list = item_list.annotate(like_count=Count('like_users')).order_by('-like_count')

    item_context_list = []
    for item in item_list:
        item_context = {
            'item': item,
            'url': '',
            'like_count': item.like_users.count(),
            'price_comma': "{:,}".format(item.price)
        }
        if item.item_images.exists():
            item_context['url'] = item.item_images.all()[0].filepath.url

        item_context_list.append(item_context)

    context = {
        'item_context_list': item_context_list,
        'sort': sort
    }
    return render(request, 'items/index.html', context)


def item_detail(request: HttpRequest, id):
    item = get_object_or_404(Item, id=id)
    item.click_count += 1
    item.save()

    is_like_on = item.like_users.filter(id=request.user.id).exists()

    item_context = {
        'item': item,
        'id': item.id,
        'title': item.title,
        'user': item.user.username,
        'content': item.content,
        'like': item.like_users.count(),
        'images': [],
        'is_like_on': is_like_on
    }
    if item.item_images.exists():
        for image in item.item_images.all():
            item_context['images'].append(image.filepath.url)

    context = {
        'item': item_context
    }
    return render(request, 'items/item_detail.html', context)


def register(request: HttpRequest):
    return render(request, 'items/register.html')


@require_POST
def delete(request: HttpRequest, id):
    item = get_object_or_404(Item, id=id)
    item.delete()

    print(f'delete. id = {id}')
    return redirect("items:index")


@require_GET
def update(request: HttpRequest, id):
    item = get_object_or_404(Item, id=id)
    context = {
        'id': item.id,
        'title': item.title,
        'price': item.price,
        'content': item.content,
        'images': []
    }
    if item.item_images:
        for image in item.item_images.all():
            context['images'].append(
                {
                    'id': image.id,
                    'url': image.filepath.url
                })

    return render(request, 'items/register.html', context)


@require_POST
def check_register(request: HttpRequest):
    data = json.loads(request.body)

    context = {
        "isValid": False,
        'title': '',
        'price': '',
        'content': '',
    }
    required_keys = ['title', 'price', 'content']

    if any(key not in data for key in required_keys):
        return JsonResponse(context)

    context['isValid'] = True
    context['title'] = data['title']
    context['price'] = data['price']
    context['content'] = data['content']

    return JsonResponse(context)


@require_POST
def do_register(request: HttpRequest):
    if request.method == 'POST':
        id = request.POST.get('id')
        if id is not None:
            item = get_object_or_404(Item, id=id)
            delete_image_id_list = request.POST.getlist('deleteImageId[]')
            images = Image.objects.filter(id__in=delete_image_id_list)
            images.delete()
        else:
            item = Item()

        item.content = request.POST.get('content')
        item.title = request.POST.get('title')
        item.price = request.POST.get('price')
        item.user = request.user

        item.save()

        file_path_list = upload_to_file(request, 'upload/')

        for file_path in file_path_list:
            image = Image()
            image.filepath = file_path
            image.item = item
            image.save()

        return JsonResponse({'status': 'success'})
    else:
        return JsonResponse({'status': 'error', 'message': 'No file uploaded or invalid request'})


@require_POST
def like(request: HttpRequest, id):
    if request.user.is_authenticated:
        item = get_object_or_404(Item, id=id)

        if item.like_users.filter(id=request.user.id).exists():
            item.like_users.remove(request.user)
        else:
            item.like_users.add(request.user)
    else:
        return redirect("items:item_detail", id)

    return redirect("items:item_detail", id)


def like_list(request):
    item_like_list = request.user.like_items.all()

    item_context_list = []
    for item in item_like_list:
        item_context = {
            'item': item,
            'image_url': '',
            'like_count': item.like_users.count(),
            'price_comma': "{:,}".format(item.price)
        }
        if item.item_images.exists():
            item_context['image_url'] = item.item_images.all()[0].filepath.url

        item_context_list.append(item_context)

    context = {
        'item_context_list': item_context_list
    }

    return render(request, 'items/like_list.html', context)


def register_item_list(request):
    item_register_list = Item.objects.filter(user=request.user)

    item_context_list = []
    for item in item_register_list:
        item_context = {
            'item': item,
            'image_url': '',
            'like_count': item.like_users.count(),
            'price_comma': "{:,}".format(item.price)
        }
        if item.item_images.exists():
            item_context['image_url'] = item.item_images.all()[0].filepath.url

        item_context_list.append(item_context)

    context = {
        'item_context_list': item_context_list
    }

    return render(request, 'items/register_item_list.html', context)

items/templates/items/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="d-flex mb-5 justify-content-center">
        <div class="mx-5">
            <form action="{% url 'items:register' %}" method="GET">
                <input type="submit" class="btn btn-danger" value="물건 등록">
            </form>
        </div>

        <div class="mx-5">
            <form method="GET">
                <div class="row justify-content-center">
                    <div class="col-auto">
                        <select name="category" class="form-select" aria-label="" style="width: 120px">
                            <option value="title" {% if category == 'title' %}selected{% endif %}>제목</option>
                            <option value="username" {% if category == 'username' %}selected{% endif %}>작성자</option>
                            <option value="content" {% if category == 'content' %}selected{% endif %}>내용</option>
                        </select>
                    </div>
                    <div class="col">
                        <input type="text" name="keyword" value="{{ keyword }}" class="form-control w-100">
                    </div>
                    <div class="col-auto">
                        <button class="btn btn-danger" style="padding-left: 28px; padding-right: 28px;">검색</button>
                    </div>
                </div>
            </form>
        </div>

        <div class="ml-2 mx-5">
            <select id="sort-by-select" class="form-select" aria-label="">
                <option value="recent" {% if sort == 'recent' %}selected{% endif %}>최신순</option>
                <option value="click" {% if sort == 'click' %}selected{% endif %}>조회순</option>
                <option value="like" {% if sort == 'like' %}selected{% endif %}>좋아요순</option>
            </select>
        </div>
    </div>

    <!-- 상품 리스트 -->
    <div class="row row-cols-1 row-cols-md-4 g-4 mx-auto w-75 pb-5">
    {% for item_context in item_context_list %}
        <div class="col">
            <div class="card h-100">
                {% if item_context.url %}
                    <img src="{{ item_context.url }}" class="card-img-top" alt="...">
                {% else %}
                    <img src="{% static "sparta.png" %}"
                         class="card-img-top" alt="...">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title"><a
                            href="{% url 'items:item_detail' item_context.item.id %}">{{ item_context.item.title }}</a>
                    </h5>
                    <div class="horizontal">
                        <p>{{ item_context.item.user }}</p>
                    </div>
                    <div class="horizontal">
                        <h6>{{ item_context.price_comma }}원</h6>
                    </div>

                    <div class="d-flex justify-content-start">
                        <p>조회수 : {{ item_context.item.click_count }} ∙ 좋아요 : {{ item_context.like_count }}</p>
                    </div>

                    <!-- 해시 태그 데이터-->
                    <div class="row row-cols-1 row-cols-md-4">
                        <div class="col">
                            <p>가전제품</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    <script>
        // select 요소에서 변경이 일어날 때마다 호출되는 함수
        var selectElement = document.getElementById('sort-by-select');
        selectElement.addEventListener('change', function (event) {
            // 선택된 옵션의 값을 가져옴
            let redirectTo = `/items/index?sort=${event.target.value}&category={{ category }}`;
            window.location.href = redirectTo;
        });
    </script>
{% endblock content %}

items/templates/items/item_detail.html
{% extends "base.html" %} {% load static %} {% block content %}
    <style>
        .detail-index {
            width: 80%;
            margin: 20px auto auto;
        }
    </style>
    <div class="detail-index">
        <div class="horizontal">
            <div class="horizontal d-flex justify-content-start">
                <a class="btn btn-danger mx-2" href="{% url 'items:index' %}">목록으로</a>
                {% if request.user.is_authenticated %}
                    {% if request.user.username == item.user %}
                        <form action="{% url 'items:update' item.id %}" method="GET">
                            <input class="btn btn-danger mx-2" type="submit" value="수정하기">
                        </form>
                        <form action="{% url 'items:delete' item.id %}" method="POST">
                            {% csrf_token %}
                            <input class="btn btn-danger mx-2" type="submit" value="삭제하기">
                        </form>
                    {% endif %}
                {% endif %}
            </div>
            <div>
                {% if item.is_like_on %}
                    <form action="{% url 'items:like' item.id %}" method="POST">
                        {% csrf_token %}
                        <input class="btn btn-danger" type="submit" value="좋아요 취소">
                    </form>
                {% else %}
                    <form action="{% url 'items:like' item.id %}" method="POST">
                        {% csrf_token %}
                        <input class="btn btn-primary" type="submit" value="좋아요">
                    </form>
                {% endif %}
            </div>
        </div>
        <hr>
        <div class="row">
            {% for image in item.images %}
                <div class="col d-flex justify-content-center">
                    <img class="detail-item-image" src="{{ image }}" alt=""/>
                </div>
            {% endfor %}
        </div>
        <hr>

        <div class="d-flex justify-content-start align-items-center">
            {% if request.user.image %}
                <img class="detail-user-image" src="{{ request.user.image.url }}" alt=""/>
            {% else %}
                <img class="detail-user-image" src="{% static "images/default_user.png" %}" alt=""/>
            {% endif %}

            <div class="mx-2">
                <h6>{{ item.user }}</h6>
            </div>
        </div>
        <hr>
        <div class="detail-content-container">
            <div class="detail_title">
                <h3>{{ item.title }}</h3>
            </div>

            <div class="detail-price">
                <h3>{{ item.price }}</h3>
            </div>

            <div class="detail-content">
                {{ item.content | linebreaksbr }}
            </div>

            <hr>
            <div class="detail-category">
                <span>좋아요 {{ item.like }} ∙ 조회 {{ item.item.click_count }}</span>
            </div>
        </div>
    </div>

{% endblock content %}

items/templates/items/like_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    {% for item_context in item_context_list %}
        <div class="horizontal">
            <div class="d-flex justify-content-start">
                {% if item_context.image_url %}
                    <img class="detail-user-image" src="{{ item_context.image_url }}" alt=""/>
                {% else %}
                    <img class="detail-user-image" src="{% static "images/default_user.png" %}" alt=""/>
                {% endif %}

                <div class="container">
                    <a href="{% url 'items:item_detail' item_context.item.id %}">
                        <h3>{{ item_context.item.title }}</h3>
                    </a>
                </div>
            </div>
            <div>
                <p>조회수 : {{ item_context.item.click_count }} ∙ 좋아요 : {{ item_context.like_count }}</p>
            </div>
        </div>
        <hr>
    {% endfor %}
{% endblock %}

items/templates/items/register.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <h1>물건 등록하기</h1>
    <div class="image-register-container d-flex justify-content-start">
        <div class="vertical">
            <button class="btn btn-danger align-self-start my-2" onclick="addImage()">이미지 등록</button>
            <button class="btn btn-danger align-self-start" onclick="deleteImage()">이미지 삭제</button>
        </div>
        <div id="image-row" class="row w-50 mx-2">
            {% for image in images %}
                <div class="col-md-3">
                    <div class="card h-20">
                        <img src="{{ image.url }}" id="{{ image.id }}" class="image-item card-img-top" alt="...">
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <div>
        <form action="{% url 'items:register' %}" method="POST">
            {% csrf_token %}

            <div class="register-title my-2">
                <h5>제목</h5>
                <label>
                    <input type="text" name="title" placeholder="제목" value="{{ title }}">
                </label>
            </div>

            <div class="register-price my-2">
                <h5>가격</h5>
                <label>
                    <input type="number" name="price" placeholder="가격을 입력하세요" value="{{ price }}">
                </label>
            </div>

            <div class="register-content my-2">
                <h5>설명</h5>
                <label>
                    <textarea name="content" rows="10" cols="100">{{ content }}</textarea>
                </label>
            </div>

        </form>

        <div class="register-hashtag my-2 d-flex justify-content-start">
            <label>
                <input type="text" name="hashtag" placeholder="해시태그 추가">
            </label>
            <button class="btn btn-danger mx-1" onclick="addHashTag()">추가</button>
            <button class="btn btn-danger mx-1" onclick="deleteHashtag()">삭제</button>
            <div class="mx-3" id="hash-tag">
            </div>
        </div>


        <div class="register-input my-2">
            <input type="hidden" value="{{ id }}" name="id">
            <button class="btn btn-danger" onclick="doRegister()">등록하기</button>
        </div>
    </div>

    <script>
        let selectedFileList = []
        let deletedImageIdList = []
        let hashTagIdList = []
        const csrfTokenInput = document.querySelector('input[name="csrfmiddlewaretoken"]');
        const titleInput = document.querySelector('input[name="title"]');
        const priceInput = document.querySelector('input[name="price"]');
        const contentInput = document.querySelector('textarea[name="content"]');
        const idInput = document.querySelector('input[name="id"]');
        const hashTagInput = document.querySelector('input[name="hashtag"]');

        function addImage() {
            var input = document.createElement('input');
            input.type = 'file';

            // 파일 선택 다이얼로그 표시
            input.click();

            // 파일 선택 다이얼로그에서 파일을 선택했을 때 이벤트 처리
            input.addEventListener('change', function (event) {
                const selectedFile = event.target.files[0];
                selectedFileList.push(selectedFile)

                var divRow = document.getElementById('image-row');

                imgSrc = URL.createObjectURL(selectedFile);

                var htmlString = `
        <div class="card h-20">
            <img src="${imgSrc}" class="image-item card-img-top" alt="...">
        </div>
`;
                var divCol = document.createElement('div');
                divCol.classList.add('col-md-3')
                divCol.innerHTML = htmlString;

                divRow.appendChild(divCol)
            });
        }

        function deleteImage() {
            let images = document.querySelectorAll(".image-item")
            for (let img of images) {
                const id = img.getAttribute('id')
                if (id !== null) {
                    deletedImageIdList.push(id)
                }
            }
            selectedFileList = []
            let divRow = document.getElementById('image-row');
            divRow.innerHTML = ''
        }

        function doRegister() {
            const csrfToken = csrfTokenInput.value.trim();
            const id = idInput.value.trim();
            const title = titleInput.value.trim();
            const price = priceInput.value.trim();
            const content = contentInput.value.trim();
            const images = document.querySelectorAll(".image-item")
            const imageSrcList = []


            for (const img of images) {
                imageSrcList.push(img.getAttribute('src'))
            }

            fetch('/items/check_register/', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrfToken
                },
                body: JSON.stringify({
                    title: title,
                    price: price,
                    content: content,
                    images: imageSrcList
                })
            })
                .then(response => response.json())
                .then(data => {
                    if (data['isValid']) {
                        let formData = new FormData();
                        for (let i = 0; i < selectedFileList.length; ++i) {
                            formData.append(`file${i}`, selectedFileList[i]);
                        }

                        for (let i = 0; i < deletedImageIdList.length; ++i) {
                            formData.append(`deleteImageId[]`, deletedImageIdList[i]);
                        }
                        if (id !== '') {
                            formData.append('id', id)
                        }
                        formData.append('title', title)
                        formData.append('price', price)
                        formData.append('content', content)

                        // AJAX 요청 보내기
                        var xhr = new XMLHttpRequest();
                        xhr.open('POST', '/items/do_register/', true); // 업로드를 처리할 URL로 변경해야 합니다.
                        xhr.onload = function () {
                            if (xhr.status === 200) {
                                console.log('파일 업로드 성공');
                                window.location = '/items/index/'
                            } else {
                                console.error('파일 업로드 실패');
                            }
                        };
                        xhr.setRequestHeader('X-CSRFToken', csrfToken);
                        xhr.send(formData);
                    }
                })
                .catch(error => console.error('Error:', error));
        }

        function addHashTag() {
            const csrfToken = csrfTokenInput.value.trim();
            let hashTagText = hashTagInput.value.trim()

            fetch('/items/check_hashtag/', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrfToken
                },
                body: JSON.stringify({
                    hashtag: hashTagText,
                })
            })
                .then(response => response.json())
                .then(data => {
                    if (data['isValid']) {
                        let divHashTag = document.getElementById('hash-tag')
                        let spanHashTag = document.createElement('span')
                        spanHashTag.classList.add('mx-2')
                        spanHashTag.innerHTML = hashTagText

                        divHashTag.appendChild(spanHashTag)
                    } else {
                        console.log('fail to add hashtag')
                    }
                })
                .catch(error => console.error('Error:', error));
        }
    </script>


{% endblock content %}

items/templates/items/register_item_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    {% for item_context in item_context_list %}
        <div class="horizontal">
            <div class="d-flex justify-content-start">
                {% if item_context.image_url %}
                    <img class="detail-user-image" src="{{ item_context.image_url }}" alt=""/>
                {% else %}
                    <img class="detail-user-image" src="{% static "images/default_user.png" %}" alt=""/>
                {% endif %}

                <div class="container">
                    <a href="{% url 'items:item_detail' item_context.item.id %}">
                        <h3>{{ item_context.item.title }}</h3>
                    </a>
                </div>
            </div>
            <div>
                <p>조회수 : {{ item_context.item.click_count }} ∙ 좋아요 : {{ item_context.like_count }}</p>
            </div>
        </div>
        <hr>
    {% endfor %}
{% endblock %}