accounts/urls.py
from django.urls import path
from django import forms
from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("delete/", views.delete, name="delete"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
    path("profile/", views.profile, name="profile"),
    path("check_name_dup/", views.check_name_dup, name="check_name_dup"),
    path("user_list/", views.user_list, name="user_list"),
    path("follow/<int:user_id>", views.follow, name="follow"),
    # path("", views.login, name="login"),
]

items/urls.py
from django.urls import path
from . import views

app_name = 'items'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('item_detail/<int:id>/', views.item_detail, name='item_detail'),
    path('register/', views.register, name='register'),
    path('check_register/', views.check_register, name='check_register'),
    path('do_register/', views.do_register, name='do_register'),
    path("delete/<int:id>/", views.delete, name="delete"),
    path("update/<int:id>/", views.update, name="update"),
    path("like/<int:id>/", views.like, name="like"),
    path("like_list/", views.like_list, name="like_list"),
    path("register_item_list/", views.register_item_list, name="register_item_list"),
]

spartamarket/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='items/index/')),
    path('items/', include('items.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    following = models.ManyToManyField('self', symmetrical=False, related_name='followers')
    image = models.ImageField(upload_to='images/', blank=True)
    comment = models.TextField(default='')
    like_products = models.ManyToManyField(
        'items.Item', related_name="like_items"
    )

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model
from django.urls import reverse


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.fields.get("password"):
            password_help_text = (
                "You can change the password " '<a href="{}">here</a>.'
            ).format(f"{reverse('accounts:change_password')}")
            self.fields["password"].help_text = password_help_text

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = UserCreationForm.Meta.fields

accounts/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash, authenticate, get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django.views.decorators.http import require_POST, require_http_methods
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, JsonResponse

from .models import *
from spartamarket.util import *

import json


def login(request: HttpRequest):
    context = {
        'error_message': ''
    }

    if request.method == "POST":
        username = request.POST.get('userid')
        user_password = request.POST.get('userpw')
        print(username, user_password)
        user = authenticate(request, username=username, password=user_password)
        print(f'user={user}')
        if user is not None:
            auth_login(request, user)
            return redirect('items:index')
        else:
            context['error_message'] = "아이디 또는 비밀번호가 일치하지 않습니다."

    return render(request, "accounts/login.html", context)


def logout(request: HttpRequest):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect("items:index")


# @acc_bp.route("/checkNameDup", methods=["POST"])
@require_POST
def check_name_dup(request: HttpRequest):
    data = json.loads(request.body)
    existing_user: User = User.objects.filter(username=data.get('username'))
    if existing_user:
        return JsonResponse({"isDuplicate": True})  # 사용자 이름이 이미 존재함
    return JsonResponse({"isDuplicate": False})


def signup(request: HttpRequest):
    if request.method == "POST":
        password = request.POST.get('regPass')
        username = request.POST.get('regName')
        email = request.POST.get('regEmail')
        image = request.POST.get('regImage')
        comment = request.POST.get('regComment')

        user = User.objects.create_user(username=username, password=password, email=email, image=image, comment=comment)
        user.save()

        auth_login(request, user)

        return redirect('items:index')
    else:
        return render(request, "accounts/signup.html")


def user_list(request: HttpRequest):
    users = User.objects.all()
    context = {
        'users': users
    }
    return render(request, 'accounts/user_list.html', context)


@require_POST
def follow(request: HttpRequest, user_id):
    if request.user.is_authenticated:
        user = get_object_or_404(get_user_model(), pk=user_id)
        if request.user != user:
            if request.user in user.followers.all():
                print('remove')
                user.followers.remove(request.user)
            else:
                print('add')
                user.followers.add(request.user)
    return redirect("accounts:user_list")


@require_POST
def delete(request: HttpRequest):
    print('delete')
    return redirect("items:index")


@require_POST
def update(request: HttpRequest):
    if request.method == 'POST':
        content = request.POST.get('content')
        file_path_list = upload_to_file(request, 'upload/')
        user = get_object_or_404(User, id=request.user.id)
        if file_path_list:
            user.image = file_path_list[0]
        user.comment = content

        user.save()

    return JsonResponse({'status': 'success'})


@login_required
@require_http_methods(["GET", "POST"])
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("items:index")
    else:
        form = PasswordChangeForm(request.user)
    context = {"form": form}
    return render(request, "accounts/change_password.html", context)


def profile(request: HttpRequest):
    return render(request, 'accounts/profile.html')

accounts/templates/accounts/change_password.html
{% extends "base.html" %}

{% block content %}
<h1>비밀번호 변경</h1>

<form action="{% url 'accounts:change_password' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">비밀번호 변경</button>
</form>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="vertical" style="padding-top: 40px">
        <div class="my-2">
            <img class="navbar-image-logo marginRight16" src="{% static "sparta.png" %}" alt="">
            <span>스파르타마켓</span>
            <img class="navbar-image-logo marginLeft16" src="{% static "sparta.png" %}" alt="">
        </div>
        <div class="vertical">
            <form method="post" class="vertical">
                {% csrf_token %}
                <input type="text" name="userid" placeholder="ID" class="custom-input">
                <input type="password" name="userpw" placeholder="Password" class="custom-input">
                <button class="button-login marginTop16">로그인</button>
            </form>
            <div id="loginBottomArea">
                <a href="{% url 'accounts:signup' %}" class="button-register">회원가입</a>
            </div>
            <div>
                <span>{{ error_message }}</span>
            </div>
        </div>
    </div>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <h3 class="customHeader">
        내 정보
    </h3>
    <div class="margin_bottom">
        {% csrf_token %}
        <div class="custom_row">
            <div class="custom_row_key">프로필 사진</div>
            <div class="custom_row_value">
                <form class="horizontal" method="post" enctype="multipart/form-data">
                    <!-- 이미지 파일 데이터에 알맞는 enctype 설정 -->
                    <div class="addImage" id="image-profile">
                        {% if request.user.image %}
                            <div>
                                <img class="profile-user-image" src="{{ request.user.image.url }}" alt="">
                            </div>
                        {% else %}
                            <div>
                                <img class="profile-user-image" src="{% static "images/default_user.png" %}" alt="">
                            </div>
                        {% endif %}
                    </div>
                    <input type="file" accept="image/*" onchange="addImage(event)">
                </form>
            </div>
        </div>
        <div class="custom_row">
            <div class="custom_row_key">계정등급</div>
            <div class="custom_row_value">{% if request.user.is_superuser %}관리자 계정{% else %}사용자 계정{% endif %}</div>
        </div>
        <div class="custom_row">
            <div class="custom_row_key">아이디</div>
            <div class="custom_row_value">{{ request.user.username }}</div>
        </div>
        <div class="custom_row">
            <div class="custom_row_key">패스워드</div>
            <div class="custom_row_value">
            <span class="passwordForm">
                <input type="password" class="changePass" style="width:0">
            </span>
                <button id="passChBtn" class="btn btn-theme-color btn-sm" onclick="createPassForm()">수정하기</button>
            </div>
        </div>
        <div class="custom_row">
            <div class="custom_row_key">이메일</div>
            <div class="custom_row_value">{{ request.user.email }}</div>
        </div>
        <div class="custom_row">
            <div class="custom_row_key">계정 생성일</div>
            <div class="custom_row_value">{{ request.user.date_joined|date:"Y-m-d H:i" }}</div>
        </div>
        <div class="custom_row">
            <div class="custom_row_key">자기 소개</div>
            <div class="custom_row_value">
                <textarea name="content" class="changeValueText">{{ request.user.comment }}</textarea>
            </div>
        </div>
        <div class="custom_row">
            <div class="custom_row_key">팔로잉 {{ request.user.following.count }}</div>
            <div class="custom_row_key">팔로워 {{ request.user.followers.count }}</div>
        </div>

    </div>

    <!-- 수정된 버튼과 모달 코드 -->
    <div class="button_area">
        <button type="button" class="btn btn-danger" onclick="updateAccount()">
            정보 수정
        </button>
    </div>

    <!-- 패스워드 검증 모달 -->
    <div class="modal fade" id="passwordModal" tabindex="-1" aria-labelledby="passwordModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="passwordModalLabel">패스워드 확인</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <!-- 패스워드 입력 폼 -->
                    <div class="mb-3">
                        <label for="passwordInput" class="form-label">패스워드</label>
                        <input type="password" class="form-control" id="passwordInput">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
                    <button type="button" class="btn btn-danger" id="confirmButton">확인</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        let selectedFile = null
        const csrfTokenInput = document.querySelector('input[name="csrfmiddlewaretoken"]');
        const contentInput = document.querySelector('textarea[name="content"]');

        function addImage(event) {
            // 파일 선택 다이얼로그에서 파일을 선택했을 때 이벤트 처리
            selectedFile = event.target.files[0];
            console.log(selectedFile)

            var divImage = document.getElementById('image-profile');

            imgSrc = URL.createObjectURL(selectedFile);

            var htmlString = `
            <img src="${imgSrc}" class="profile-user-image" alt="...">
`;
            var divInnerImage = document.createElement('div');
            divInnerImage.innerHTML = htmlString;

            divImage.innerHTML = ''
            divImage.appendChild(divInnerImage)
        }

        function updateAccount() {
            let formData = new FormData();
            const content = contentInput.value.trim()
            const csrfToken = csrfTokenInput.value.trim()

            formData.append('file', selectedFile)
            formData.append('content', content)

            console.log('content')
            let xhr = new XMLHttpRequest();
            xhr.open('POST', '/accounts/update/', true);
            xhr.onload = function () {
                if (xhr.status === 200) {
                    console.log('업로드 성공');
                    window.location = '/items/index/'
                } else {
                    console.error('파일 업로드 실패');
                }
            }
            xhr.setRequestHeader('X-CSRFToken', csrfToken);
            xhr.send(formData);
        }

        function deleteAccount() {
            console.log('delete')
        }


        function createPassForm() {
            var btn = document.querySelector("#passChBtn");
            var passwordForm = document.querySelector(".passwordForm");
            var inputForm = document.querySelector(".changePass");

            if (btn.innerHTML === "수정하기") {
                btn.innerHTML = "수정완료"
                btn.setAttribute("class", "btn btn-sm changePass btn-sub-color");
                inputForm.removeAttribute('style');
                inputForm.removeAttribute('disabled');
                inputForm.focus();
            } else {
                btn.innerHTML = "수정하기"
                inputForm.setAttribute('disabled', "true");
                btn.setAttribute("class", "btn btn-sm changePass btn-theme-color");
            }
        }

        function createTextForm() {
            const btn = document.querySelector("#commChBtn");
            const commentArea = document.querySelector('.changeValueText')
            if (btn.innerHTML === "수정하기") {
                btn.innerHTML = "수정완료"
                btn.setAttribute("class", "btn btn-sm btn-sub-color");
                commentArea.removeAttribute('disabled');
                commentArea.focus();
                commentArea.setSelectionRange(commentArea.value.length, commentArea.value.length);
            } else {
                btn.innerHTML = "수정하기"
                btn.setAttribute("class", "btn btn-sm btn-theme-color");
                // 이전 값으로 textarea를 갱신
                console.log(commentArea);
                commentArea.setAttribute('disabled', 'true');
            }
        }

    </script>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <style scoped>
        .signup-center {
            display: flex;
            justify-content: center;
            align-items: center;
        }

        #signupForm {
            flex-direction: column;
        }

        .custom-input {
            width: 300px;
            margin-top: -5px;
        }

        .file-input-container {
            display: flex;
            justify-content: center;
            align-items: center;
        }

        #imagePreview {
            width: 100px;
            height: 100px;
            margin-left: -100px;
            display: none;
        }

    </style>

    <div class="signup-center">
        <img class="navbar-image-logo marginRight16" src="{% static "sparta.png" %}" alt="">
        <span>회원가입</span>
        <img class="navbar-image-logo marginLeft16" src="{% static "sparta.png" %}" alt="">
    </div>

    <form id="signupForm" class="signup-center" method="post" enctype="multipart/form-data"
          action="{% url 'accounts:signup' %}">
        {% csrf_token %}
        <span class="regNameState"></span><br>
        <input type="text" class="custom-input" name="regName" placeholder="아이디를 입력해주세요"><br>
        <input type="password" class="custom-input" name="regPass" placeholder="패스워드를 입력해 주세요"><br>
        <input type="password" class="custom-input" name="chkPass" placeholder="패스워드를 다시 입력해 주세요"><br>
        <span class="regMailState"></span><br>
        <input type="email" name="regEmail" class="custom-input" placeholder="이메일을 형식에 맞춰 작성해 주세요"><br>
        <textarea name="regComment" class="custom-input" style="margin-top: 40px;" placeholder="소개글을 작성해 주세요."></textarea>
        <button type="button" style="width: 300px;" class="btn btn-danger mt-2" onclick="signupCheck()">회원가입
        </button>
    </form>

    <script>
        let usernameBool = false;
        const usernameInput = document.querySelector('input[name="regName"]');
        const usernameState = document.querySelector('.regNameState');
        const userpassInput = document.querySelector('input[name="regPass"]');
        const userCheckpassInput = document.querySelector('input[name="chkPass"]');
        const csrfTokenInput = document.querySelector('input[name="csrfmiddlewaretoken"]');

        usernameInput.addEventListener('keyup', function () {
            const username = usernameInput.value.trim();
            const csrfToken = csrfTokenInput.value.trim();
            if (username.length > 4) {
                fetch('/accounts/check_name_dup/', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': csrfToken
                    },
                    body: JSON.stringify({username: username})
                })
                    .then(response => response.json())
                    .then(data => {
                        console.log(data)
                        if (data.isDuplicate) {
                            usernameState.innerHTML = "사용중인 아이디입니다.";
                            usernameBool = false;
                        } else {
                            usernameState.innerHTML = "사용가능한 아이디입니다.";
                            usernameBool = true;
                        }
                    })
                    .catch(error => console.error('Error:', error));
            } else {
                usernameState.innerHTML = "아이디는 5자리 이상으로 설정해주세요.";
                usernameBool = false;
            }
        });

        function signupCheck() {
            const userPass = userpassInput.value.trim();
            const userChkPass = userCheckpassInput.value.trim();
            if (!usernameBool) {
                alert("입력하신 아이디를 확인해주세요");
            } else if (userPass !== userChkPass) {
                alert("패스워드가 서로 일치하지 않습니다.");
            } else {
                document.getElementById("signupForm").submit();
            }
        }
    </script>
{% endblock %}

accounts/templates/accounts/update.html
{% extends "base.html" %} {% block content %}
<h1>Update Article</h1>

<form action="{% url 'accounts:update' %}" method="POST">
  {% csrf_token %} {{ form.as_p}}

  <button type="submit">수정하기</button>
</form>

{% endblock content %}

accounts/templates/accounts/user_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    {% for user in users %}
        {% if request.user != user %}
            <div class="horizontal">
                <div class="d-flex justify-content-start">
                    {% if user.image %}
                        <img class="detail-user-image" src="{{ user.image.url }}" alt=""/>
                    {% else %}
                        <img class="detail-user-image" src="{% static "images/default_user.png" %}" alt=""/>
                    {% endif %}

                    <div class="container">
                        <h3>{{ user.username }}</h3>
                    </div>
                </div>
                <div>
                    <form action="{% url "accounts:follow" user.id %}" method="POST">
                        {% csrf_token %}
                        {% if request.user in user.followers.all %}
                            <button type="submit" class="btn btn-danger">언팔로우</button>
                        {% else %}
                            <button type="submit" class="btn btn-danger">팔로우</button>
                        {% endif %}
                    </form>
                </div>
            </div>
            <hr>
        {% endif %}
    {% endfor %}
{% endblock %}