accounts/urls.py
from django.urls import path
from django import forms
from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("delete/", views.delete, name="delete"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
    path("profile/", views.profile, name="profile"),
    path("check_name_dup/", views.check_name_dup, name="check_name_dup"),
    path("user_list/", views.user_list, name="user_list"),
    path("follow/<int:user_id>", views.follow, name="follow"),
    # path("", views.login, name="login"),
]

items/urls.py
from django.urls import path
from . import views

app_name = 'items'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('item_detail/<int:id>/', views.item_detail, name='item_detail'),
    path('register/', views.register, name='register'),
    path('check_register/', views.check_register, name='check_register'),
    path('do_register/', views.do_register, name='do_register'),
    path("delete/<int:id>/", views.delete, name="delete"),
    path("update/<int:id>/", views.update, name="update"),
    path("like/<int:id>/", views.like, name="like"),
    path("like_list/", views.like_list, name="like_list"),
    path("register_item_list/", views.register_item_list, name="register_item_list"),
]

spartamarket/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='items/index/')),
    path('items/', include('items.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>스파르타마켓</title>
  </head>
  <body>
    <nav id="nav-bar">
      <div class="nav-container">
          <a class="nav-logo" href="{% url 'items:index' %}">
              <img class="navbar-image-logo" src="{% static "sparta.png" %}" alt="">
              <span style="font-family: 'EF_jejudoldam'">스파르타마켓</span>
          </a>
          <div>
              <a href="{% url 'accounts:user_list' %}" class="nav-btn">사용자 리스트</a>
              {% if request.user.is_authenticated %}
                  <a href="{% url 'accounts:profile' %}" class="nav-btn">내정보</a>
                  <a href="{% url 'items:like_list' %}" class="nav-btn">관심 목록</a>
                  <a href="{% url 'items:register_item_list' %}" class="nav-btn">등록 제품</a>
                  <a href="{% url 'accounts:logout' %}" class="nav-btn">로그아웃</a>
              {% else %}
                  <a href="{% url 'accounts:login' %}" class="nav-btn">로그인</a>
              {% endif %}
          </div>
      </div>
    </nav>

    <div class="content-wrap customBody">{% block content %} {% endblock content %}</div>
  </body>
</html>